### ISSUE TITLE
Jest test (rogue-client.test.js) failing

### ISSUE THREAD

**Issue by techcobweb** [chrisesharp/roguelike#12]
`npm test` to run the unit tests... bang.

FAIL  test/rogue-client.test.js
  ● monster connects to server › should see other entities die

    TypeError: Cannot read property '0' of undefined

      367 |       
      368 |       if (bot2started && event === EVENTS.delete) {
    > 369 |         let other = bot1.client.getItemsAt(pos1.x, pos1.y, pos1.z)[0];
          |                     ^
      370 |         expect(other.getDescription()).toEqual("goblin corpse");
      371 |         bot1.stop();
      372 |         done();

      at Object.ready (test/rogue-client.test.js:369:21)
      at GoblinBot.ready (src/monsters/bot.js:23:20)
      at GoblinBot.refresh (src/monsters/bot.js:42:14)
      at callback (src/monsters/bot.js:11:80)
      at Socket.<anonymous> (src/client/entity-client.js:52:13)
      at Socket.Emitter.emit (node_modules/socket.io-client/node_modules/component-emitter/index.js:145:20)
      at Socket.emitEvent (node_modules/socket.io-client/build/socket.js:264:20)
      at Socket.onevent (node_modules/socket.io-client/build/socket.js:251:18)
      at Socket.onpacket (node_modules/socket.io-client/build/socket.js:215:22)
      at Manager.Emitter.emit (node_modules/socket.io-client/node_modules/component-emitter/index.js:145:20)
      at Manager.ondecoded (node_modules/socket.io-client/build/manager.js:204:15)
      at Decoder.Emitter.emit (node_modules/socket.io-parser/node_modules/component-emitter/index.js:145:20)
      at Decoder.add (node_modules/socket.io-parser/dist/index.js:117:23)
      at Manager.ondata (node_modules/socket.io-client/build/manager.js:196:22)
      at Socket.Emitter.emit (node_modules/engine.io-client/node_modules/component-emitter/index.js:145:20)
      at Socket.onPacket (node_modules/engine.io-client/lib/socket.js:387:16)
      at WS.<anonymous> (node_modules/engine.io-client/lib/socket.js:196:14)
      at WS.Emitter.emit (node_modules/engine.io-client/node_modules/component-emitter/index.js:145:20)
      at WS.onPacket (node_modules/engine.io-client/lib/transport.js:103:10)
      at WS.onData (node_modules/engine.io-client/lib/transport.js:96:10)
      at WebSocket.ws.onmessage (node_modules/engine.io-client/lib/transports/websocket.js:113:12)
      at WebSocket.onMessage (node_modules/engine.io-client/node_modules/ws/lib/event-target.js:132:16)
      at Receiver.receiverOnMessage (node_modules/engine.io-client/node_modules/ws/lib/websocket.js:825:20)
      at Receiver.dataMessage (node_modules/engine.io-client/node_modules/ws/lib/receiver.js:437:14)
      at Receiver.getData (node_modules/engine.io-client/node_modules/ws/lib/receiver.js:367:17)
      at Receiver.startLoop (node_modules/engine.io-client/node_modules/ws/lib/receiver.js:143:22)
      at Receiver._write (node_modules/engine.io-client/node_modules/ws/lib/receiver.js:78:10)
      at Socket.socketOnData (node_modules/engine.io-client/node_modules/ws/lib/websocket.js:900:35)

**Comment by techcobweb** [comment]
This one could be intermittent. Sometimes it passes, sometimes it fails.

**Comment by chrisesharp** [comment]
I *think* this is fixed in the TS version now
